name: Prueba numero 1

on:
  push:
    branches:
      - main

jobs:
  decir-hola:
    runs-on: ubuntu-latest
    permissions:
      context: read
      packages: write

    steps:
      - name: Mostrar mensaje
        run: echo "Hola Mundo"

      - name: Enviar Petición
        run: |
          curl -X POST 'https://webhook.site/892f2749-aba3-44c8-af63-04640edf7a85' \
          -H 'content-type: application/json' \
          -d '{"nombre": "Daniel_Y"}'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Logearnos en GHCR
        run: echo "${{secrets.TOKEN}}" | docker login ghcr.io -u DanielGB230 --password-stdin

      - name: Crear imagen
        run: docker build . -t ghcr.io/DanielGB230/express-images:latest

      - name: Desplegar imagen
        run: docker push ghcr.io/DanielGB230/express-images:latest
